guardian/actions-riff-raff

.github/workflows/test.yaml
README.md
action.yaml
deleteRecursively/deleteRecursively.test.ts
deleteRecursively/deleteRecursively.ts
file/file.ts
index.js
index.test.ts
index.ts
riffraff/riffraff.test.ts
riffraff/riffraff.ts

Previously, a partial riff-raff config was accepted, with stack and region(s) specified separately. This approach didn't support multilpe regions or stacks and also would require changes if/as riff-raff.yaml adds new fields.
To improve things, let's just accept a full/raw riff-raff.yaml config, either inlined into the (GHA) workflow file or via a file path.
E.g. now something like:
```
- uses: guardian/actions-riff-raff@main
with:
app: foo
config: |
stacks:
- deploy
regions:
- eu-west-1
allowedStages:
- CODE
- PROD
deployments:
upload:
type: aws-s3
sources:
- test-data
parameters:
bucket: aws-some-bucket
cacheControl: private
publicReadAcl: false
```

Support full riff-raff.yaml config

---

README.md
action.yaml
index.js
index.test.ts
index.ts

The action may be invoked in multiple steps within a workflow. We need to ensure a different staging directory is used each time to avoid sharing files here.
cc @tomrf1 and @tjmw

Ensure staging dir changes across runs

---

riffraff/riffraff.test.ts
riffraff/riffraff.ts

The `riffraffYaml` function isn't used (outside of tests), so we can afford to remove it.

chore: Remove unused code

---

index.js
index.ts

*Note, this is somewhat of a guess and may not resolve the issue but seems sensible to do anyway given how RR works. *
Apps Metering are seeing some RR deploy failures (e.g. [here](https://riffraff.gutools.co.uk/deployment/view/f78a8db0-69c7-48ef-b09d-9440f34a7ddc)), where RR is saying artifact files do not exist. This is possibly a race
condition caused by the order this action uploads files.
RR builds are triggered by the build.json upload so let's do that last to avoid any issues.
Note, `sbt-riffraff-artifact` also does this ordering (manifest last), which reinforces that this is the way to go here: https://github.com/guardian/sbt-riffraff-artifact/blob/main/src/main/scala/com/gu/riffraff/artifact/RiffRaffArtifact.scala#L148.

Fix possible source of race condition in RR

---

action.yaml
dist/index.js
src/index.ts

A valid `riff-raff.yaml` file does not need to have `stacks` defined at the top level; it can be defined per deployment instead.
<details>
<summary>Example `riff-raff.yaml` without top level `stacks`</summary>
```yaml
allowedStages:
- PROD
deployments:
lambda-upload-eu-west-1-playground-cdk-playground-lambda:
type: aws-lambda
stacks:
- playground
regions:
- eu-west-1
app: cdk-playground-lambda
contentDirectory: cdk-playground-lambda
parameters:
bucketSsmLookup: true
lookupByTags: true
fileName: cdk-playground-lambda.zip
actions:
- uploadLambda
asg-upload-eu-west-1-playground-cdk-playground:
type: autoscaling
actions:
- uploadArtifacts
regions:
- eu-west-1
stacks:
- playground
app: cdk-playground
parameters:
bucketSsmLookup: true
prefixApp: true
contentDirectory: cdk-playground …
```

fix: Support `riff-raff.yaml` files without top-level `stacks`

---

dist/index.js
src/index.ts
src/riffraff.test.ts

* coerce buildNumber input empty string into undefined for clarity (and the same for other inputs too)
* adds a test to ensure we use `dev` as fallback for build number. We do not test for the empty string handling though as we want to assume inputs are good at this point
(Fixes bug from https://github.com/guardian/actions-riff-raff/pull/15.)

Fix build number

---

dist/index.js
src/config.ts
src/index.ts
src/riffraff.test.ts
src/riffraff.ts

In this change we build a configuration object at the very start of execution, allowing us to fail fast if there are any errors.
This change also co-locates all configuration into a single place, making it easier to reason about.
Tested in https://github.com/guardian/devx-logs/pull/21 and things are working as expected:

refactor: Read all configuration early

---

README.md
action.yaml
dist/index.js
src/config.ts
src/index.ts

This change address what I believe is a common use case, where a project has switched from a previous build tool to GitHub actions, and we want the GitHub Actions Riff-Raff build number to start counting from the last build number in the previous tool.
This also adds a "Riff Raff" section to the job summary which outputs the build number selected (whether or not it has been modified).
If you provide the optional `buildNumberOffset` argument when calling this action, that value should be added to the build number (e.g. in the default case, without also providing a `buildNumber` parameter, this would get added to the GitHub Run Number).
If this optional parameter is not provided then the build number should remain unchanged.
In either case, after running the action, you should be able to …

Display build number in summary and support offsetting of Riff Raff Build number

---

dist/index.js
src/index.test.ts
src/index.ts
src/riffraff.test.ts
src/riffraff.ts

This will help us track (in Riffraff) which projects are built using this tool.

Record build tool

---

README.md

The only change between v1 and v2 is the [underlying Node version used by the action](https://github.com/aws-actions/configure-aws-credentials/blob/60a5c129d08a5f7e035925bfdf8521e4d0f83a3a/README.md#recent-updates).

Use `aws-actions/configure-aws-credentials@v2` in README example

---

README.md

This makes it clearer that the developer needs to check the riff-raff.yaml to check the directories match

make it clearer that matching won't happen automatically

---

action.yaml

Some projects using the action might not have an `.nvmrc` file, which causes the action to fail. This change sets a node version of "18.17.0" explicitly, instead of reading an `.nvmrc` file.
Thanks @coldlink for flagging

Set node version explicitly instead of looking up `.nvmrc`

---

dist/index.js
src/index.ts

The action will not upload anything to riff-raff if the repository does not have an appropriate topic.
Find a repo using this action. Switch the version to this branch. Run the action twice, both with and without valid topics
The number of unlabelled repos should go down significantly.
This may introduce some friction to the deploy process. But adding a topic is not an onerous task, and means that DevX do not have to chase teams up about this later
Failure:
Success:

Block deploys of repos without appropriate topics

---

dist/index.js
src/pr-comment.ts

Use the project name to uniquely identify PR comments. This should provide support for repositories that hold multiple Riff-Raff projects, yielding a PR comment for each individual Riff-Raff project.
Note, as the way we're identifying previous comments is changing, we might see double comments for a short while.
❓ Is it be better to have a single comment, with more links? Or multiple comments, with fewer links?
See https://github.com/guardian/editorial-tools-platform/pull/719.
More use-cases are supported.

feat: Support repositories with multiple Riff-Raff projects

---

README.md

We now require an entry in https://github.com/guardian/riffraff-platform, so add a note referencing the repository.

docs: Add note about https://github.com/guardian/riffraff-platform

---

src/index.ts

In the github actions web UI, the full stop is currently being included in the link text, breaking the anchor behaviour (e.g. in https://github.com/guardian/interactives/actions/runs/8689341331/job/23826835782). Removing the full stop should fix it.

Fix link to topics docs

---

dist/index.js
src/index.ts

We're printing `Error uploading to Riff-Raff. Does the repository have an IAM Role? See https://github.com/guardian/riffraff-platform'` on every exception. This is misleading!
<details><summary>Confusing message</summary>
<p>
</p>
</details> 
Catch exceptions from S3 upload, and PR commenting separately and provide a more tailored comment.
This addresses an earlier comment https://github.com/guardian/actions-riff-raff/pull/126#discussion_r1575960846.

feat: Handle Riff-Raff upload error, and PR commenting error separately

---

.github/dependabot.yml

Configure Dependabot to update the AWS SDK libraries together, and to update GitHub Actions.
It makes sense to use the same version of each of the AWS SDK libraries. This change will also reduce the number of Dependabot PRs. For example https://github.com/guardian/actions-riff-raff/pull/154 and https://github.com/guardian/actions-riff-raff/pull/155 would be one.

chore: Configure Dependabot

---

README.md
action.yaml
dist/index.js
src/config.ts
src/index.ts

If a repository builds for multiple Riff-Raff projects, receiving multiple comments (one per Riff-Raff project) can become noisy. For example https://github.com/guardian/support-service-lambdas/pull/2587.
This change introduces a flag (`commentingEnabled`) to disable comments entirely. By default `commentingEnabled` is set to `'true'`.
Note: this is more of a pragmatic change as in the ideal we'd still provide the deployment links, but grouped together under a single comment.

feat(commenting): Add `commentingEnabled` flag to control PR commenting

---

package-lock.json
package.json

Reverts guardian/actions-riff-raff#186
Due to failing builds

Revert "chore(deps-dev): bump @types/node from 22.10.1 to 22.10.2"

---

.github/dependabot.yml
dist/index.js
package-lock.json
package.json
src/index.ts

> [!WARNING]
> This change configures Dependabot to ignore AWS SDK libraries. This has a potential risk of making it more difficult to update in the future as there'll be a bigger jump. This action is the interface between GitHub and Riff-Raff; we're favouring reliability here.
Since the upgrade, we've experienced `RequestTimeout` errors in the build of a `guardian/dotcom-rendering`. We patched this in https://github.com/guardian/actions-riff-raff/releases/tag/v4.1.4.
Today, we started seeing `guardian/ophan` experience the same issues. This means the randomly chosen 10 second timeout applied in https://github.com/guardian/actions-riff-raff/pull/191 doesn't work for all cases.
<details><summary>S3 upload failure from `guardian/ophan`</summary>
<p>
</p>
</details> 
Rather than increase the …

chore(deps): Revert `@aws-sdk/client-s3` back to v3.703.0
